name: idorm_admin_flutter
description: application for admin

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  flutter_svg: ^1.1.4
  permission_handler: ^10.0.0
  http: ^0.13.5
  logger: ^2.0.2+1
  shared_preferences: ^2.0.15

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.9
  package_info_plus: ^3.0.3
  webview_flutter: ^4.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#71A1FE"
  image: assets/splash.png
  android_12:
    icon_background_color: "#71A1FE"
    image: assets/splash12.png
